#!/bin/sh
# shell function for calepin

cpdir="$HOME/Dropbox/Apps/Calepin"
name=$1
file=$cpdir/$name.md
touch $file
if [[ $CALEPIN_EDITOR > "" ]]; then
	type -P $CALEPIN_EDITOR &>/dev/null && $CALEPIN_EDITOR $file || open -a $CALEPIN_EDITOR $file
else
  open -e $file
fi
