#!/bin/sh
# shell function for CP

if [[ $CALEPIN_DIR == "" ]]; then
    CALEPIN_DIR="$HOME/Dropbox/Apps/Calepin"
fi
CP_FILE=$CALEPIN_DIR/$1.md
touch $CP_FILE
if [[ $CALEPIN_EDITOR > "" ]]; then
		first=`echo $CALEPIN_EDITOR | cut -d" " -f1`
	type -P $first &>/dev/null && $CALEPIN_EDITOR $CP_FILE || open -a "$CALEPIN_EDITOR" $CP_FILE
else
  open -e $CP_FILE
fi
